Repository ApolloTVofficial/Claws, pull requests merged in 2019-05, with the labels that each got.

#136 Add FilmXY Provider
  src/scrapers/providers/index.js
  src/scrapers/providers/movies/FilmXY.js
Labels: Code Review Required

#139 Add OpenloadMovie Provider
  src/scrapers/providers/index.js
  src/scrapers/providers/movies/OpenloadMovie.js
Labels: Functional Test - Pass

#137 Add Putlocker Provider
  src/scrapers/providers/index.js
  src/scrapers/providers/movies/Putlocker.js
Labels: Code Review Required, Functional Test - Pass

#138 Add Reddit Provider
  src/scrapers/providers/index.js
  src/scrapers/providers/movies/Reddit.js
Labels: Functional Test - Pass

#143 Add GrabTheBeast Provider
  src/scrapers/providers/index.js
  src/scrapers/providers/tv/GrabTheBeast.js
Labels: Functional Test - Pass

#144 feat(provider): return provider endpoint & filter providers
  src/api/generalRoutes.js
  src/api/resolveLinks.js
  src/scrapers/providers/index.js
Labels: Enhancement

#149 Add PutlockerONL Provider
  src/scrapers/providers/index.js
  src/scrapers/providers/universal/PutlockerONL.js
Labels: Functional Test Required

#123 Update Quality Utility Function
  src/scrapers/providers/movies/AZMovies.js
  src/scrapers/providers/movies/BFMovies.js
  src/scrapers/resolvers/RapidVideo.js
  src/scrapers/resolvers/XStreamCDN.js
  src/utils/index.js
Labels: Pending Client Changes
