Repository ApolloTVofficial/Claws, pull requests merged in 2019-04, with the labels that each got.

#59 GoWatchSeries Rework
  src/scrapers/providers/index.js
  src/scrapers/providers/tv/GoWatchSeries.js
  src/scrapers/providers/universal/GoWatchSeries.js
Labels: testing required

#25 Add SolarMovie Provider (Squash Merge)
  src/scrapers/providers/index.js
  src/scrapers/providers/universal/SolarMovie.js
Labels: Ready to Merge

#78 feat(provider) add Series9 universal provider
  src/scrapers/providers/index.js
  src/scrapers/providers/universal/Series9.js
Labels: Ready to Merge

#79 feat(provider) add Onmovies universal provider
  src/scrapers/providers/index.js
  src/scrapers/providers/universal/Onmovies.js
Labels: Code Review Required, Ready to Merge

#84 Show beta interface depending on parameters
  .env.dist
  server.js
Labels: Code Review Required, Ready to Merge

#85 Move the debug interface to /ui
  public/ui/index.html
  server.js
Labels: Code Review Required

#83 fix(provider) remove 5Movies due to access ban
  src/scrapers/providers/universal/SolarMovie.js
Labels: Code Review Required

#81 chore(providers) organize and cleanup providers
  src/scrapers/providers/archive/movies/MovieFiles.js
  src/scrapers/providers/archive/tv/AfdahTV.js
  src/scrapers/providers/archive/universal/5movies.js
  src/scrapers/providers/index.js
  src/scrapers/providers/movies/BFMovies.js
  src/scrapers/providers/universal/123Movie.js
Labels: Code Review Required

#87 Add route to get NTP from Claws.
  src/api/authRoutes.js
Labels: Code Review Required

#80 fix(RapidVideo) show the properly quality for resolved links
  src/scrapers/resolvers/RapidVideo.js
  src/scrapers/resolvers/resolve.js
  src/utils/WsWrapper.js
Labels: Ready to Merge

#90 fix(web-interface) use NTP time during auth
  public/ui/index.html
Labels: Functional Test - Pass, Ready to Merge

#82 feat(provider) add SockShare universal provider
  src/scrapers/providers/index.js
  src/scrapers/providers/universal/SockShare.js
Labels: Ready to Merge

#91 fix(package.json) remove trailing comma
  package.json
Labels: Ready to Merge

#94 feat(provider) add MeliMedia movie provider
  src/scrapers/providers/archive/movies/GoStream.js
  src/scrapers/providers/index.js
  src/scrapers/providers/movies/MeliMedia.js
  src/scrapers/resolvers/MeliMedia.js
  src/scrapers/resolvers/resolve.js
Labels: Functional Test - Pass, Ready to Merge

#101 fix(MeliMedia) filter out audio tracks
  src/scrapers/providers/movies/MeliMedia.js
Labels: Functional Test Required

#92 fix(WsWrapper) update setHeadInfo() to check for isResultOfScrape
  src/utils/WsWrapper.js
Labels: Under Discussion

#103 Rework DDL Resolving
  src/scrapers/providers/BaseProvider.js
  src/scrapers/providers/movies/DLFilm.js
  src/scrapers/providers/movies/MeliMedia.js
  src/scrapers/providers/universal/FardaDownload.js
  src/scrapers/resolvers/DDLResolver.js
  src/scrapers/resolvers/FardaDownload.js
  src/scrapers/resolvers/MeliMedia.js
  src/scrapers/resolvers/resolve.js
Labels: Code Review Required, Functional Test - Pass

#102 feat(provider) add MoviesWeb TV provider
  src/scrapers/providers/index.js
  src/scrapers/providers/tv/MoviesWeb.js
Labels: Code Review Required, Functional Test - Pass

#108 Search With IMDB ID (ODB)
  src/scrapers/providers/universal/ODB.js
Labels: Code Review Required, Functional Test Required

#109 Patch Generate Values Script
  generate-env-values.sh
Labels: Ready to Merge

#106 Add HeyDL Universal Provider
  src/scrapers/providers/index.js
  src/scrapers/providers/universal/HeyDL.js
Labels: Code Review Required, Functional Test - Pass

#111 Add DebugDummy Provider (Testing Purposes)
  src/scrapers/providers/index.js
  src/scrapers/providers/universal/DebugDummy.js
Labels: Ready to Merge

#113 Filter Extensions (DDL Providers)
  src/scrapers/resolvers/resolve.js
  src/utils/WsWrapper.js
  src/utils/createEvent.js
  src/utils/index.js
Labels: Code Review Required, Functional Test Required

#114 Improve Quality Function
  src/scrapers/resolvers/DDLResolver.js
  src/scrapers/resolvers/resolve.js
  src/utils/WsWrapper.js
  src/utils/index.js
Labels: Code Review Required

#115 Revert Quality Check Ordering
  src/utils/index.js
Labels: Code Review Required

#116 Initial RD Functionality
  src/api/resolveLinks.js
  src/scrapers/providers/BaseProvider.js
  src/scrapers/providers/movies/AZMovies.js
  src/scrapers/providers/movies/Afdah.js
  src/scrapers/providers/movies/BFMovies.js
  src/scrapers/providers/movies/DLFilm.js
  src/scrapers/providers/movies/MeliMedia.js
  src/scrapers/providers/movies/StreamM4u.js
  src/scrapers/providers/tv/MoviesWeb.js
  src/scrapers/providers/tv/ProjectFreeTV.js
  src/scrapers/providers/tv/SeriesFree.js
  src/scrapers/providers/tv/SwatchSeries.js
  src/scrapers/providers/universal/123Movie.js
  src/scrapers/providers/universal/DebugDummy.js
  src/scrapers/providers/universal/FardaDL.js
  src/scrapers/providers/universal/GoWatchSeries.js
  src/scrapers/providers/universal/HeyDL.js
  src/scrapers/providers/universal/ODB.js
  src/scrapers/providers/universal/Onmovies.js
  src/scrapers/providers/universal/Series8.js
  src/scrapers/providers/universal/Series9.js
  src/scrapers/providers/universal/SockShare.js
  src/scrapers/providers/universal/SolarMovie.js
  src/scrapers/resolvers/resolve.js
  src/utils/createEvent.js
  src/utils/rd.js
Labels: Code Review - Pass, Functional Test Required

#118 Add TwoDDL Provider (RD-Universal)
  src/api/resolveLinks.js
  src/scrapers/providers/index.js
  src/scrapers/providers/rd/universal/TwoDDL.js
  src/scrapers/resolvers/resolve.js
  src/utils/createEvent.js
Labels: Code Review Required

#126 Add DDLSpot & MyVideoLinks RD Providers
  package-lock.json
  src/scrapers/providers/index.js
  src/scrapers/providers/rd/universal/DDLSpot.js
  src/scrapers/providers/rd/universal/MyVideoLinks.js
  src/scrapers/providers/rd/universal/TwoDDL.js
Labels: Code Review Required, Functional Test - Pass, Pending Client Changes

#128 DDLSpot Handle Colons
  src/scrapers/providers/rd/universal/DDLSpot.js
Labels: Code Review Required

#130 Get & Pass Resolver Name (RD)
  server.js
  src/scrapers/resolvers/resolve.js
  src/utils/rd.js
Labels: Code Review Required, Functional Test - Pass

#127 Cloudflare Bypass
  package-lock.json
  package.json
  src/scrapers/providers/BaseProvider.js
  src/scrapers/providers/index.js
  src/scrapers/providers/movies/LavinMovie.js
  src/utils/constants.js
  src/utils/queue.js
Labels: Ready to Merge

#132 StreamM4U CF Patch
  src/scrapers/providers/index.js
  src/scrapers/providers/movies/StreamM4U.js
Labels: Under Discussion
